/**
 * LLM provider contract — shared across Claude, OpenAI, OpenAI-compat
 * (DeepSeek/Qianwen/Ollama/MiniMax), MiniMax Token Plan, and Wenxin.
 *
 * The message / content-block layout follows the Anthropic API (richest of
 * the three). Providers that use a different wire format convert internally.
 */

// ---- Message content blocks ------------------------------------------------

export interface LLMTextBlock {
  type: 'text'
  text: string
}

export interface LLMToolUseBlock {
  type: 'tool_use'
  /** Unique id generated by the LLM — we echo it back in the matching tool_result. */
  id: string
  name: string
  input: Record<string, unknown>
}

export interface LLMToolResultBlock {
  type: 'tool_result'
  /** Matches the `id` of the originating tool_use. */
  toolUseId: string
  /** Textual result the LLM reads. Artifacts are UI-only and not included here. */
  content: string
  isError?: boolean
}

export type LLMContentBlock = LLMTextBlock | LLMToolUseBlock | LLMToolResultBlock

export interface LLMMessage {
  role: 'user' | 'assistant' | 'system'
  /** Plain string for simple text turns; blocks for multi-part (tool use / tool results). */
  content: string | LLMContentBlock[]
}

// ---- Tool schema passed to the LLM -----------------------------------------

export interface ToolSchema {
  name: string
  description: string
  /** JSON Schema object describing the tool's parameters. */
  inputSchema: Record<string, unknown>
}

// ---- Stream options --------------------------------------------------------

export interface StreamOptions {
  model: string
  messages: LLMMessage[]
  systemPrompt?: string
  maxTokens?: number
  temperature?: number
  /**
   * If provided, the LLM may emit tool_use events. Providers that don't
   * support tool calling (e.g. Wenxin) ignore this and degrade to text-only.
   */
  tools?: ToolSchema[]
}

// ---- Stream events emitted by providers ------------------------------------

/**
 * Providers emit these events in order. A single assistant turn may interleave
 * text and tool_use — the final event is always `stop` (or `error`).
 *
 * When the model decides to call tools, the sequence is:
 *   (optional text_delta*)
 *   tool_use_start(id, name)     ← fires when the tool block starts
 *   tool_use(id, name, input)    ← fires once input JSON is fully parsed
 *   ... possibly more tool blocks ...
 *   stop(reason='tool_use')
 *
 * The Agent is expected to execute all collected tool_use inputs, append the
 * results to `messages`, and re-invoke `stream()`.
 */
export type StreamEvent =
  | { type: 'text_delta'; delta: string }
  | { type: 'tool_use_start'; id: string; name: string }
  | { type: 'tool_use'; id: string; name: string; input: Record<string, unknown> }
  | { type: 'stop'; reason: 'end_turn' | 'tool_use' | 'max_tokens' | 'stop_sequence' | string }
  | { type: 'error'; message: string }

export interface ILLMProvider {
  readonly providerId: string
  stream(options: StreamOptions): AsyncGenerator<StreamEvent>
  /**
   * Whether this provider supports tool calling. Agents check this to decide
   * whether to send a `tools` array at all.
   */
  readonly supportsTools?: boolean
}
